### ISSUE TITLE
Python track design

### ISSUE THREAD

**Issue by theSage21** [PyJaipur/Summer-of-Algorithm#21]
This track is intended as a basic starting point for learning python. We assume that the person is able to use a computer and a browser but has no idea about how to program.

Through this track they should be able to do the following at the minimum:

- [ ] School-level math
- [ ] Simple string manipulation
- [ ] How to use a list
- [ ] How to use a dictionary
- [ ] How to take user input
- [ ] How to print things on the screen

While designing this track keep in mind the following things:

- Provide links to tutorials instead of explaining things.
- Each task can only have a small description. Avoid page scrolling.
- Link to official docs if possible, otherwise blog posts and videos are also ok.
- Ask them to practice using https://repl.it or https://www.codechef.com/ide instead of wasting time getting python to run on their machine.
- Each task can only have a max of 5 links to avoid overloading the participant.
- Each task must have a verifiable exercise which can prove that the participant has learned the topic.

**Comment by anchal7299** [comment]
I have picked some topics for the tasks for this track. Please suggest any changes need to be made. 
- **Task 1:**  Python Syntax 
- **Task 2:**  User input Program
- **Task 3:**  Basic Operators
- **Task 4:**  Control Flow
- **Task 5:**  Loops 
- **Task 6:**  Functions
- **Task 7:**  Strings
- **Task 8:**  Lists 
- **Task 9:**  Using a Dictionary
- **Task 10:** Classes

**Comment by theSage21** [comment]
This looks good 😊.

Please do your work in a separate fork and open a pull request to master.

**Comment by theSage21** [comment]
@anchal7229 I was thinking maybe we can leave out loops, dictionaries and do them in the DSA track?

Same goes for classes. Perhaps we can do them in a OOP track? What do you think?

**Comment by anchal7299** [comment]
I Agree with you

**Comment by anchal7299** [comment]
I agree with you

**Comment by avni-srivastava** [comment]
Can't we add Numpy or Pandas ,Scipy, tensorflow any one or 2 from these on the place of loops or dictionaries as these topics will make the track look more catchy and also upgrade it.

**Comment by anubhavsharma430** [comment]
**Task 12** Data Structures-1 {Stack, Queue}
**Task 13** Data Structures-2 {Linked-List,Tree} + Recursion
**Task 14** the different techniques to avoid Loops as loops give damage to the architecture of the Core
**Task 15** Sorting Algorithms {Insertion, Quick, Bubble, Selection, Radix, Heap} + Searching
**Task 16** String Matching Naive, KMP Algorithm + Matrix Chain Multiplication + Eucledion algorithm, Extended Eucledion algorithm
**Task 17** Numpy Functions + numpy array functions
**Task 18** Pandas DataFrame Functions

We can include these all so that a person gets hands on experience on algorithms use in the world. Also it gives them the thinking ability and courage to make an algorithm work without getting fear of errors

**Comment by theSage21** [comment]
> Can't we add Numpy or Pandas ,Scipy, tensorflow any one or 2 from these on the place of loops or dictionaries as these topics will make the track look more catchy and also upgrade it.

Since this track is meant for people who are new to programming we can't add those to the Python track. Perhaps those would be ok if we were doing a Data science / ML track.

**Comment by theSage21** [comment]
> **Task 12** Data Structures-1 {Stack, Queue}
> **Task 13** Data Structures-2 {Linked-List,Tree} + Recursion
> **Task 14** the different techniques to avoid Loops as loops give damage to the architecture of the Core
> **Task 15** Sorting Algorithms {Insertion, Quick, Bubble, Selection, Radix, Heap} + Searching
> **Task 16** String Matching Naive, KMP Algorithm + Matrix Chain Multiplication + Eucledion algorithm, Extended Eucledion algorithm
> **Task 17** Numpy Functions + numpy array functions
> **Task 18** Pandas DataFrame Functions
> 
> We can include these all so that a person gets hands on experience on algorithms use in the world. Also it gives them the thinking ability and courage to make an algorithm work without getting fear of errors

Maybe you want to put these in the DSA track instead of the Python track? @anchal7299 can create a separate issue for that and set guidelines.

**Comment by theSage21** [comment]
@anchal7299 ye python track ka kaam continue karein? @Shivank98 and I had a call and we're thinking that we can turn this into a learning management platform for colleges.

Let us know if you'll have time to work on this.

**Comment by anchal7299** [comment]
Yes , I will be happy to help in building this platform
